---
services: docker

language: python
python:
  - 3.6
cache: pip

install:
  - pip install molecule docker

before_script:
  - cd ..
  - mv ansible-role-{{ cookiecutter.pretty_role_name | lower | replace(" ", "-") }} hadrienpatte.{{ cookiecutter.pretty_role_name | lower | replace(" ", "_") }}
  - cd hadrienpatte.{{ cookiecutter.pretty_role_name | lower | replace(" ", "_") }}

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
